apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: '61.3.0' # ALWAYS pin versions. Never use "latest".
    helm:
      releaseName: kube-prometheus-stack
      values: |
        grafana:
          adminPassword: admin # Simple local password
        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            route:
              group_by: ['namespace']
              group_wait: 10s
              group_interval: 10s
              repeat_interval: 10m
              receiver: 'healer-webhook'
              routes:
              - matchers:
                - alertname = "KubePodCrashLooping"
                receiver: 'healer-webhook'
            receivers:
            - name: 'healer-webhook'
              webhook_configs:
              - url: 'http://healer-core.healer.svc.cluster.local:80/alert'
                send_resolved: true
        prometheus:
          prometheusSpec:
            retention: 2d # Keep 2 days of metrics locally
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # CRITICAL: This chart is massive. Server-side apply prevents "metadata.annotations: Too long" errors.
