apiVersion: v1
kind: Service
metadata:
  name: healer-core
  namespace: healer
spec:
  selector:
    app: healer-core
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
